import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Albuquerque Catch a Ride",
  description: "Generated by create next app | Web Application that enables users to either provide or find many vehic related services.",
};

type RootlayoutProps = {
  children: React.ReactNode;
}


export default function RootLayout(props: RootlayoutProps){
  const { children } = props;
  return (
      <html lang="en" suppressHydrationWarning>
      <body>
      <Navbar/>
      {children}
      <Footer/>
      </body>
      </html>
  )
}
